#!/usr/bin/env python3
import sys
from passlib.hash import pbkdf2_sha512

if len(sys.argv) != 2:
    print("Usage: genhash <YourNewPassword>")
    sys.exit(1)

password = sys.argv[1]
hash = pbkdf2_sha512.using(rounds=350000).hash(password)
print(hash)
